//AUTH
export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';

//UPLOADS
export const FETCH_UPLOADS = 'FETCH_UPLOADS';
export const FETCH_UPLOAD_DATA_OR_DOWNLOAD = 'FETCH_UPLOAD_DATA_OR_DOWNLOAD';
export const PREPARE_FILE_UPLOAD = 'PREPARE_FILE_UPLOAD';
export const UPLOAD_FILE = 'UPLOAD_FILE';
export const UPDATE_UPLOAD_PRIVACY = 'UPDATE_UPLOAD_PRIVACY';
export const DELETE_UPLOAD = 'DELETE_UPLOAD';
export const HIDE_MODAL = 'HIDE_MODAL';